---
# tasks file for ansible-role-aws-infra
- name: upload SSH keys
  local_action:
    module: ec2_key
    name: "{{ lookup('env', 'USER') }}"
    key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  run_once: yes

- name: Configure Security Group
  local_action:
    module: ec2_group
    name: default
    description: "TODO Should be set from inventory"
    state: present
    rules: "{{ aws_firewall_rules }}"
  register: ec2_group

- debug:
    var: ec2_group

- name: create VM instance started
  local_action:
    module: ec2
    key_name: "{{ lookup('env', 'USER') }}"
    instance_type: "{{ aws_offering }}"
    instance_tags:
      Name: "{{ inventory_hostname }}"
    image: "{{ aws_template }}"
    group_id: "{{ ec2_group.group_id }}"
    wait: true
    vpc_subnet_id: subnet-791fd312
    assign_public_ip: yes    
    count_tag: 
      Name: "{{ inventory_hostname }}"
    exact_count: 1
  register: ec2

- block:
  - name: Allocate elastic IP
    local_action:
      module: ec2_eip
      public_ip: "{{ aws_public_ip }}"
      device_id: "{{ ec2.instance_ids|first }}"

  - name: add additional volume to VM
    local_action:
      module: ec2_vol
      name: "{{ item.1.name | default('DATA-' + ec2.instance_ids|first + '-' + item.0|string) }}"
      instance: "{{ ec2.instance_ids|first }}"
      volume_size: "{{ item.1.volume_size }}"
      volume_type: "{{ item.1.volume_type }}"
      delete_on_termination: yes
    with_indexed_items:
   - "{{ aws_disks }}"
  when: ec2.changed

- name: waiting for SSH connection
  wait_for_connection:
    delay: 10
    timeout: 300