---
# tasks file for ansible-role-aws-infra
- name: upload SSH keys
  local_action:
    module: ec2_key
    name: "{{ lookup('env', 'USER') }}"
    key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  run_once: yes

- name: Configure Security Group
  local_action:
    module: ec2_group
    name: default
    description: "TODO Should be set from inventory"
    state: present
    rules: "{{ aws_firewall_rules }}"
  register: ec2_group

- debug:
    var: ec2_group

- name: create VM instance started
  local_action:
    module: ec2
    key_name: "{{ lookup('env', 'USER') }}"
    instance_type: "{{ aws_offering }}"
    image: "{{ aws_template }}"
    group_id: "{{ ec2_group.group_id }}"
    wait: true
    vpc_subnet_id: subnet-791fd312
    assign_public_ip: yes    
  register: ec2

